# docker-compose.yml

version: "3"

services:
    app:
        build:
            context: .
            dockerfile: runner.Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - front
            - base
        networks:
            - app-network
    base:
        build:
            context: .
            dockerfile: base.Dockerfile
        depends_on:
            - front
        networks:
            - app-network
    front:
        build:
            context: .
            dockerfile: front.Dockerfile
        networks:
            - app-network
    nginx:
        image: nginx:latest
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
